name: Build & Upload
on: [workflow_dispatch]
jobs:
  universalBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: ls -l && ebhqwbhewqh

      - name: Make Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/MCScanner.jar
          asset_name: MCScanner.jar
          asset_content_type: application/java-archive