name: Build & Upload
on:
  workflow_dispatch:
    inputs:
      Version:
        description: 'Version number for release'
        required: true
        default: '1.2'

jobs:
  universalBuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build
        run: ./gradlew build

      - name: Make Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: v${{ github.event.inputs.Version }}
          tag_name: v${{ github.event.inputs.Version }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/MCScanner.jar
          asset_name: MCScanner.jar
          asset_content_type: application/java-archive